AllCops:
  RubyInterpreters:
    - ruby


Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/PerceivedComplexity:
  Max: 12

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/BlockLength:
  Max: 40

Metrics/BlockNesting:
  Max: 4